### PR TITLE
fix missing draft info on dashboard

### LINKED ISSUE #90: Dashboard icons missing some draft data
- [x] Audio durations on the dashboard not including unsaved audio
- [x] Make sure unsaved images are shown on the dashboard
- [x] Make sure you get a dashboard draft, even if you haven't added a title yet (currently not showing as draft on dashboard if only audio, image, and/or podcast distribution is added, but is saved in local storage)

### PR DESCRIPTION
**Pull request by sandikbarr**
Fixes #90 dashboard draft info.
 - [ ] Audio durations on the dashboard not including unsaved audio --> should compute duration for files !isDestroy(), including those that are only in local storage and not yet persisted to CMS
 - [ ] Make sure unsaved images are shown on the dashboard --> If only an image was set, the dashboard tile was showing as an add new story plus-sign button
 - [ ] Make sure you get a dashboard draft, even if you haven't added a title yet --> If only image, audio, and or clean/explicit was set, the dashboard tile was showing as an add new story plus-sign button

### CODE REVIEW

File: src/app/home/directives/home-story.component.ts [hunk 1]
```diff
@@ -95,4 +65,30 @@ export class HomeStoryComponent implements OnInit {
     }
   }
 
+  get isPlusSign(): boolean {
+    return this.story.isNew && !this.story.isStored()
```
Comment (sandikbarr) [inline src/app/home/directives/home-story.component.ts]: sadly, I have realized this is incorrect :(

Comment (cavis) [inline src/app/home/directives/home-story.component.ts]: maybe `this.story.isNew && !this.story.changed()` ?

Comment (cavis) [inline src/app/home/directives/home-story.component.ts]: i was purposefully avoiding calling `changed()` earlier, as i didn't want to load-related.  But now that we have to... may as well.

Comment (sandikbarr) [inline src/app/home/directives/home-story.component.ts]: That works. Thanks. Now I just need to figure out what to do if they set Explicit/Clean and nothing else, or maybe why Explicit/Clean isn't registering as changed...

File: src/app/shared/model/audio-version.model.ts [hunk 2]
```diff
@@ -127,7 +127,7 @@ export class AudioVersionModel extends BaseModel {
   }
 
   changed(field?: string | string[], includeRelations = true): boolean {
-    if (this.isNew && this.files.length === 0) {
+    if (this.isNew && this.files.length === 0 && this.explicit === undefined) {
```
Comment (sandikbarr) [inline src/app/shared/model/audio-version.model.ts]: This also has the effect of prompting the user on story edit that they have unsaved changes if they have set Clean/Explicit and nothing else, which seems correct to me.

Comment (cavis) [inline src/app/shared/model/audio-version.model.ts]: Hmm... having to manually check for explicit here seems like a symptom of something else.

Maybe try giving it a default value of `""` (empty string) at the top of this file?  Could also mess around with the decode/encode functions, to allow a blank value rather than defaulting to 'Clean'.

Or maybe if clean really is the default, the top should be `public explicit = 'Clean'`?

Comment (sandikbarr) [inline src/app/shared/model/audio-version.model.ts]: On the question of what the default should be, do we support not including the tag `<itunes:explicit>` if explicit is not set or is empty string? Or do we always include the tag?

**Comment by gcampo88** [comment]
this looks good to me! @sandikbarr are you planning to rework the `explicit` options as default `''`, vs. `explicit`/`clean` in this PR or should that be its own small PR?

**Comment by sandikbarr** [comment]
Had to get tests working again, but this is now updated with an empty string default for explicit and a falsey check on explicit in `changed()`
