### PR TITLE
Fix tests for angular final

### LINKED ISSUE #25: fix component tests
In RC5, `overrideComponent` doesn't quite work right - it doesn't actually mock out the dependencies/constructors/bindings of the component.  When RC6 hits, this should be resolved.  Should go back and try to fix the component tests.

### PR DESCRIPTION
**Pull request by cavis**
Fixes #25.

### CODE REVIEW

File: src/testing/index.ts [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+
+import { MockCmsService } from './mock.cms.service';
+import { currentCms } from './components';
+import { matchers } from './matchers';
+
+// custom jasmine matchers
+beforeEach(() => jasmine.addMatchers(matchers));
+
+// normal exports
+export { cit, create, contain, direct, provide, stub, stubPipe } from './components';
```
Comment (cavis) [inline src/testing/index.ts]: These are the primary helpers for running a component test.  They do a lot of the boilerplate-legwork of angular testing.

File: src/testing/helpers.ts [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+
+// find a component within a debug element
+export function findComponent(el: DebugElement, tagName: string): any {
+  let subEl = el.query(By.css(tagName));
+  expect(subEl).not.toBeNull(`Unable to find component ${tagName}`);
+  return subEl.componentInstance;
+}
+
+// nicely stringify a debug/native element
+export function niceEl(el: DebugElement|any): string {
```
Comment (cavis) [inline src/testing/helpers.ts]: There are probably libraries that could do this.  But since I needed to blacklist all the `_ngSomething` attributes anyways, and nuke all the angular-bindings-comments, I went with the custom magic-box approach.

File: src/testing/components.ts [hunk 3]
```diff
@@ -0,0 +1,103 @@
...
+import { StubRouterLinkDirective } from './stub.routerlink.directive';
+
+interface ComponentTestCallback {
+  (fix: ComponentFixture<any>, el: DebugElement, comp: any, done?: Function): any;
+}
+
+// component test-it up!
+export function cit(desc: string, testFn: ComponentTestCallback) {
+  return it(desc, function(done) {
+    TestBed.configureTestingModule({
```
Comment (cavis) [inline src/testing/components.ts]: This is the actual angular test-setup code (similar to how a module is configured).

**Comment by cavis** [comment]
@sandikbarr this is ready to go.  I didn't really change any tests, so you may want to breeze over most of those files.

The meat-and-potatoes of this PR is in the `src/testing` directory.  Abstracts away some of the angular component-testing setup, and provides nicer looking helper-methods to create components, stub providers, mock cms requests, etc.

File: src/testing/helpers.ts (hunk 2 above)
Comment (sandikbarr) [inline src/testing/helpers.ts]: does the job!

File: src/testing/matchers.ts [hunk 4]
```diff
@@ -0,0 +1,95 @@
...
+      if (!found) {
+        return fail(`Cannot find css '${cssQuery}' in '${actual}'`);
+      }
+
+      // TODO: ng-model bindings not being reflected in element values yet
+      let value;
+      if (attrName === 'value') {
+        value = found.nativeElement.getAttribute('ng-reflect-model');
+        if (value && found.nativeElement.value === value) {
+          console.log('TODO: remove this hacky code, cause ng-model works again');
```
Comment (sandikbarr) [inline src/testing/matchers.ts]: 😄
